// Typically, events are generated by user actions such as mouse clicks and key
//presses. In addition, events can be generated from code.

// To generate an event programmatically, you follow these steps:
// - First, create a new Event object using Event constructor.
// - Then, trigger the event using element.dispatchEvent() method.

// --------------------------------------------
//              Event constructor
// --------------------------------------------
  // let event = new Event(type, [,options])

// *** type ***
// is a string that specifies the event type such as 'click'.

// *** options ***
// is an object with two optional properties:

// - bubbles: is a boolean value that determines if the event bubbles or not. If it
//is true then the event is bubbled and vice versa.

// - cancelable: is also a boolean value that specifies whether the event is
//cancelable when it is true.

  // {bubbles: false, cancelable: false}

// ----------------------------------------------------
//                 dispatchEvent method
// ----------------------------------------------------
// After creating an event, you can fire it on a target element using the 
//dispatchEvent() method

// element.dispatchEvent(event)

let btn = document.querySelector('.btn')

btn.addEventListener('click', () => {
  alert('Mouse clicked!')
})

let clickEvent = new Event('click')

btn.dispatchEvent(clickEvent) // fires when entering the page...